// Generated by Wrangler on Wed Apr 17 2024 16:39:47 GMT+0200 (Central European Summer Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	MY_KV_NAMESPACE: KVNamespace;
	MY_BUCKET: R2Bucket;
	MY_DB: D1Database;
}
